// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn9yvzOz8HFZtEJ0mRlCE579O_0BCMJkQ',
    appId: '1:77879755454:android:94d83860a67f495b53d4ef',
    messagingSenderId: '77879755454',
    projectId: 'tuchati-553f8',
    storageBucket: 'tuchati-553f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7dFi0ixQRazYcBZ6UDUMAzKJqMygmGs8',
    appId: '1:77879755454:ios:a93c7d4a180e9b7453d4ef',
    messagingSenderId: '77879755454',
    projectId: 'tuchati-553f8',
    storageBucket: 'tuchati-553f8.appspot.com',
    androidClientId: '77879755454-te09bdq386bhmhcnkdos9e20ufirm3cc.apps.googleusercontent.com',
    iosClientId: '77879755454-7r1p33b2l6m92fpla7aji93j7imknoge.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
